//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gouthamapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public int empid_i { get; set; }
        public string emp_designation_vc { get; set; }
        public string Emp_Role_n { get; set; }
        public string Employee_Name__vc { get; set; }
        public string username_vc { get; set; }
        public string password_vc { get; set; }
        public Nullable<System.DateTime> joindate_d { get; set; }
    }
}
